# Paths
data_dir: "../data/images"
resized_dir: "../data/resized"
output_path: "../data/attributes.json"
attribute_prompt_path: "../prompts/attribute_prompt.txt"

# Image settings
image_size:
  - 256
  - 256

